services:
  efood_database:
    image: postgres:16.3-alpine3.20
    container_name: efood_database
    environment:
      - POSTGRES_DB=efood
      - POSTGRES_USER=efood
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "efood"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432

  efood_app:
    image: efood
    build: .
    container_name: efood_app
    env_file: docker-compose.env
    ports:
      - 8000:8000
    depends_on:
      efood_database:
        condition: service_healthy
    volumes:
      - ./:/app
